### ISSUE TITLE
bwce 2.3.3 with FTL Plugin - Problem during StartUp 

### ISSUE THREAD

**Issue by haarchri** [TIBCOSoftware/bwce-docker#13]
We use an OpenShift Environment 3.7 and use the following DockerImage:

> FROM docker-registry:5000/dev/rhel7:latest
> 
> LABEL "com.tibco.BWCE.image.pure" ""
> LABEL "com.tibco.BWCE.image.version" "2.3.3"
> 
> COPY startup.sh /scripts/
> COPY setup.sh /scripts/
> COPY bwce-runtime-2.3.3.zip /resources/bwce-runtime/
> 
> RUN chmod 755 /scripts/*.sh && yum -y update && yum -y install unzip ssh
> 
> COPY TIB_bwpluginftl_6.4.0_v2_bwce-runtime.zip /resources/addons/plugins/
> COPY ftl_linux_client_libraries.zip /resources/addons/lib/
> 
> COPY com.tibco.ftl_5.2.1.004.zip /resources/addons/jars/
> RUN unzip /resources/addons/jars/com.tibco.ftl_5.2.1.004.zip -d /resources/addons/jars/
> 
> ENTRYPOINT ["/scripts/start.sh"]
> 

Now we got the following problem during the startup:

> org.osgi.framework.BundleException: Exception in Activator.start() of bundle com.tibco.ftl.
> --
>   | at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:792)
>   | at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
>   | at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:936)
>   | at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:319)
>   | at org.eclipse.osgi.container.Module.doStart(Module.java:571)
>   | at org.eclipse.osgi.container.Module.start(Module.java:439)
>   | at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
>   | at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
>   | at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
>   | at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:242)
>   | at org.eclipse.osgi.container.Module.doStart(Module.java:571)
>   | at org.eclipse.osgi.container.Module.start(Module.java:439)
>   | at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:172)
>   | at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:393)
>   | at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:412)
>   | at org.eclipse.osgi.launch.Equinox.start(Equinox.java:115)
>   | at com.tibco.bw.thor.admin.node.commands.StartLocalCommand.start(StartLocalCommand.java:480)
>   | at com.tibco.bw.thor.admin.node.commands.StartLocalCommand.doExecute(StartLocalCommand.java:180)
>   | at com.tibco.bw.thor.management.cli.commands.AbstractCommand.execute(AbstractCommand.java:62)
>   | at org.apache.felix.gogo.commands.basic.AbstractCommand.execute(AbstractCommand.java:35)
>   | at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:474)
>   | at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:400)
>   | at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
>   | at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)
>   | at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)
>   | at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)
>   | at com.tibco.bw.thor.management.cli.commands.AbstractMain.o00000(AbstractMain.java:482)
>   | at com.tibco.bw.thor.management.cli.commands.AbstractMain.o00000(AbstractMain.java:451)
>   | at com.tibco.bw.thor.management.cli.commands.AbstractMain.mainLoop(AbstractMain.java:179)
>   | at com.tibco.bw.thor.admin.node.Main.main(Main.java:36)
>   | Caused by: java.lang.UnsatisfiedLinkError: no nghttp2 in java.library.path
>   | at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
>   | at java.lang.Runtime.loadLibrary0(Runtime.java:870)
>   | at java.lang.System.loadLibrary(System.java:1122)
>   | at Activator.start(Activator.java:21)
>   | at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
>   | at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
>   | at java.security.AccessController.doPrivileged(Native Method)
>   | at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
>   | ... 29 more
>   | Root exception:
>   | java.lang.UnsatisfiedLinkError: no nghttp2 in java.library.path
>   | at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
>   | at java.lang.Runtime.loadLibrary0(Runtime.java:870)
>   | at java.lang.System.loadLibrary(System.java:1122)
>   | at Activator.start(Activator.java:21)
>   | at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
>   | at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
>   | at java.security.AccessController.doPrivileged(Native Method)
>   | at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
>   | at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
>   | at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:936)
>   | at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:319)
>   | at org.eclipse.osgi.container.Module.doStart(Module.java:571)
>   | at org.eclipse.osgi.container.Module.start(Module.java:439)
>   | at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
>   | at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
>   | at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
>   | at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:242)
>   | at org.eclipse.osgi.container.Module.doStart(Module.java:571)
>   | at org.eclipse.osgi.container.Module.start(Module.java:439)
>   | at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:172)
>   | at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:393)
>   | at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:412)
>   | at org.eclipse.osgi.launch.Equinox.start(Equinox.java:115)
>   | at com.tibco.bw.thor.admin.node.commands.StartLocalCommand.start(StartLocalCommand.java:480)
>   | at com.tibco.bw.thor.admin.node.commands.StartLocalCommand.doExecute(StartLocalCommand.java:180)
>   | at com.tibco.bw.thor.management.cli.commands.AbstractCommand.execute(AbstractCommand.java:62)
>   | at org.apache.felix.gogo.commands.basic.AbstractCommand.execute(AbstractCommand.java:35)
>   | at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:474)
>   | at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:400)
>   | at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
>   | at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)
>   | at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)
>   | at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)
>   | at com.tibco.bw.thor.management.cli.commands.AbstractMain.o00000(AbstractMain.java:482)
>   | at com.tibco.bw.thor.management.cli.commands.AbstractMain.o00000(AbstractMain.java:451)
>   | at com.tibco.bw.thor.management.cli.commands.AbstractMain.mainLoop(AbstractMain.java:179)
>   | at com.tibco.bw.thor.admin.node.Main.main(Main.java:36)
>   | 08:32:54.699 INFO  [main] com.tibco.bw.frwk.engine.BWEngine - TIBCO-BW-FRWK-300002: BW Engine [Main] started successfully.
>   | 08:32:57.466 INFO  [main] com.tibco.thor.frwk - AppNode (OSGi Framework) started in 8 seconds
>   | -------------------------------------------
> 

and

> 08:32:57.897 ERROR [CM Configuration Updater (Update: pid={http://ns.tibco.com/bw/sharedresource/ftl}FTLRealmServerConnection.3a6fbc73-339e-4723-8c4b-72ccd21cad9b )] c.t.b.s.r.c.SharedResourceModulePropertyTracker - TIBCO-BW-SR-FRWK-502000: Failed to create SharedResource [ftl_receiver.module.FTLRealmServerConnection] for Module [FTL_Receiver.module:1.0.0.20180712122101], DeploymentUnit [FTL_Receiver:1.0].
>    <CausedBy> com.tibco.bw.sharedresource.ftl.runtime.exception.FTLRealmServerConnectionCreateException: TIBCO-BW-SR-FTL-500004: Environment variable FTL_HOME is not defined. Failed to create FTL Realm Server Connection Shared Resource [ftl_receiver.module.FTLRealmServerConnection] due to exception [java.lang.UnsatisfiedLinkError: no tibftljni in java.library.path]. FTLRealmServerURL=[http://ftl-realmserver.dev.svc:13131 ], FTLSecondaryRealmServerURL=[], FTLAppName=[EIPCN_PoC_FTL_Test_Receiver_V01], FTLAppInstanceID=[null]..
>    <CausedBy> java.lang.UnsatisfiedLinkError: no tibftljni in java.library.path
> 08:32:58.410 ERROR [Framework Event Dispatcher: Equinox Container: b032ac51-7786-0018-10d8-b1c74c1311e1] c.t.b.thor.runtime.model.Constituent - The following error has occurred for "name: FTL_Receiver.module version: 1.0.0.20180712122101 bundle name: FTL_Receiver.module " which needs to be resolved.

any ideas to fix the problem ?

**Comment by haarchri** [comment]
Additional Information:

We do Step 3) 5a) 5b)* with ZIP Folder and UNZIP via DockerFile
https://docs.tibco.com/pub/bwce/2.3.3/doc/html/GUID-BAC1EBEA-0E6E-4DF7-B9B3-944A473EF8A3.html

**Comment by haarchri** [comment]
we test a other solution 
with the following docker file:

> FROM docker-registry.default.svc:5000/base-images/tibco-bwce:latest
> 
> LABEL "com.tibco.BWCE.image.pure" ""
> LABEL "com.tibco.BWCE.image.version" "2.3.3"
> 
> COPY *bwce-runtime.zip /resources/addons/plugins/
> COPY *libraries.zip /resources/addons/lib/
> 
> COPY com.tibco.ftl_5.2.1.004.zip /resources/addons/jars/
> RUN unzip -j /resources/addons/jars/com.tibco.ftl_5.2.1.004.zip -d /resources/addons/jars/
> RUN rm -rf /resources/addons/jars/com.tibco.ftl_5.2.1.004.zip
> 
> ENTRYPOINT ["/scripts/start.sh"]


and then we get the following error:


> 09:09:16.860 INFO  [main] com.tibco.thor.frwk - bwappnode TIBCO BusinessWorks Container Edition version 2.3.3, build V12, 2018-02-20 initialized using logging config /tmp/tibco.home/bwce/2.3/config/logback.xml
> --
>   | 09:09:18.199 ERROR [main] com.tibco.thor.frwk - TIBCO-THOR-FRWK-CMN-500001: Failed to install bundle from [/tmp/tibco.home/bwce/2.3/system/hotfix/shared/tibftl.jar]
>   | java.lang.Exception: Found a duplicate bundle within the same folder file:/tmp/tibco.home/bwce/2.3/system/hotfix/shared/tibftl.jar
>   | at com.tibco.bw.thor.management.common.BW6RepoUtil.installFromFolder(BW6RepoUtil.java:507) [com.tibco.bw.thor.management.common_1.4.803.007.jar:na]
>   | at com.tibco.bw.thor.management.common.BW6RepoUtil.installFromFolder(BW6RepoUtil.java:351) [com.tibco.bw.thor.management.common_1.4.803.007.jar:na]
>   | at com.tibco.bw.thor.admin.node.commands.StartLocalCommand.installFromSystem(StartLocalCommand.java:1759) [com.tibco.bw.thor.admin.node_1.4.802.008.jar:na]
>   | at com.tibco.bw.thor.admin.node.commands.StartLocalCommand.install(StartLocalCommand.java:1316) [com.tibco.bw.thor.admin.node_1.4.802.008.jar:na]
>   | at com.tibco.bw.thor.admin.node.commands.StartLocalCommand.installProduct(StartLocalCommand.java:1346) [com.tibco.bw.thor.admin.node_1.4.802.008.jar:na]
>   | at com.tibco.bw.thor.admin.node.commands.StartLocalCommand.start(StartLocalCommand.java:391) [com.tibco.bw.thor.admin.node_1.4.802.008.jar:na]
>   | at com.tibco.bw.thor.admin.node.commands.StartLocalCommand.doExecute(StartLocalCommand.java:180) [com.tibco.bw.thor.admin.node_1.4.802.008.jar:na]
>   | at com.tibco.bw.thor.management.cli.commands.AbstractCommand.execute(AbstractCommand.java:62) [com.tibco.bw.thor.management.cli_1.4.500.002.jar:na]
>   | at org.apache.felix.gogo.commands.basic.AbstractCommand.execute(AbstractCommand.java:35) [org.apache.karaf.shell.console-2.3.1.jar:na]
>   | at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:474) [org.apache.karaf.shell.console-2.3.1.jar:na]
>   | at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:400) [org.apache.karaf.shell.console-2.3.1.jar:na]
>   | at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108) [org.apache.karaf.shell.console-2.3.1.jar:na]
>   | at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183) [org.apache.karaf.shell.console-2.3.1.jar:na]
>   | at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120) [org.apache.karaf.shell.console-2.3.1.jar:na]
>   | at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89) [org.apache.karaf.shell.console-2.3.1.jar:na]
>   | at com.tibco.bw.thor.management.cli.commands.AbstractMain.o00000(AbstractMain.java:482) [com.tibco.bw.thor.management.cli_1.4.500.002.jar:na]
>   | at com.tibco.bw.thor.management.cli.commands.AbstractMain.o00000(AbstractMain.java:451) [com.tibco.bw.thor.management.cli_1.4.500.002.jar:na]
>   | at com.tibco.bw.thor.management.cli.commands.AbstractMain.mainLoop(AbstractMain.java:179) [com.tibco.bw.thor.management.cli_1.4.500.002.jar:na]
>   | at com.tibco.bw.thor.admin.node.Main.main(Main.java:36) [com.tibco.bw.thor.admin.node_1.4.802.008.jar:na]
>   | TIBCO-THOR-ADMIN-CLI-500001: Start of AppNode failed. <CausedBy> TIBCO-THOR-FRWK-CMN-500001: Failed to install bundle from [/tmp/tibco.home/bwce/2.3/system/hotfix/shared/tibftl.jar]

**Comment by haarchri** [comment]
we fixed the problem 

the symbolic links was missing after we zipped the following location:
`<FTL-HOME>/components/shared/1.0.0/plugins...`
